import 'package:flutter/material.dart';

class TopicConfig {
  final int totalWords;
  final String difficulty;
  final IconData icon;
  final Color color;
  final String estimatedTime;

  const TopicConfig({
    required this.totalWords,
    required this.difficulty,
    required this.icon,
    required this.color,
    required this.estimatedTime,
  });
}

class TopicConfigsRepository {
  static const Map<String, TopicConfig> _topicConfigs = {
    'schools': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.school,
      color: Colors.blue,
      estimatedTime: '15 min',
    ),
    'examination': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.quiz,
      color: Colors.orange,
      estimatedTime: '12 min',
    ),
    'family': TopicConfig(
      totalWords: 30,
      difficulty: 'Beginner',
      icon: Icons.family_restroom,
      color: Colors.pink,
      estimatedTime: '18 min',
    ),
    'animals': TopicConfig(
      totalWords: 40,
      difficulty: 'Beginner',
      icon: Icons.pets,
      color: Colors.brown,
      estimatedTime: '20 min',
    ),
    'food': TopicConfig(
      totalWords: 35,
      difficulty: 'Beginner',
      icon: Icons.fastfood,
      color: Colors.red,
      estimatedTime: '18 min',
    ),
    'drinks': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.local_drink,
      color: Colors.teal,
      estimatedTime: '12 min',
    ),
    'clothing': TopicConfig(
      totalWords: 30,
      difficulty: 'Beginner',
      icon: Icons.checkroom,
      color: Colors.purple,
      estimatedTime: '15 min',
    ),
    'weather': TopicConfig(
      totalWords: 20,
      difficulty: 'Beginner',
      icon: Icons.wb_sunny,
      color: Colors.yellow,
      estimatedTime: '10 min',
    ),
    'colors': TopicConfig(
      totalWords: 15,
      difficulty: 'Beginner',
      icon: Icons.format_color_fill,
      color: Colors.deepPurple,
      estimatedTime: '8 min',
    ),
    'numbers': TopicConfig(
      totalWords: 20,
      difficulty: 'Beginner',
      icon: Icons.numbers,
      color: Colors.blueGrey,
      estimatedTime: '10 min',
    ),
    'time': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.access_time,
      color: Colors.indigo,
      estimatedTime: '12 min',
    ),
    'days_of_week': TopicConfig(
      totalWords: 7,
      difficulty: 'Beginner',
      icon: Icons.calendar_today,
      color: Colors.green,
      estimatedTime: '5 min',
    ),
    'months': TopicConfig(
      totalWords: 12,
      difficulty: 'Beginner',
      icon: Icons.calendar_month,
      color: Colors.lightGreen,
      estimatedTime: '7 min',
    ),
    'seasons': TopicConfig(
      totalWords: 4,
      difficulty: 'Beginner',
      icon: Icons.nightlight_round,
      color: Colors.orangeAccent,
      estimatedTime: '4 min',
    ),
    'body': TopicConfig(
      totalWords: 35,
      difficulty: 'Beginner',
      icon: Icons.accessibility,
      color: Colors.redAccent,
      estimatedTime: '18 min',
    ),
    'emotions': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.sentiment_satisfied,
      color: Colors.pinkAccent,
      estimatedTime: '12 min',
    ),
    'house': TopicConfig(
      totalWords: 40,
      difficulty: 'Beginner',
      icon: Icons.home,
      color: Colors.blue,
      estimatedTime: '20 min',
    ),
    'kitchen': TopicConfig(
      totalWords: 30,
      difficulty: 'Beginner',
      icon: Icons.kitchen,
      color: Colors.orange,
      estimatedTime: '15 min',
    ),
    'bathroom': TopicConfig(
      totalWords: 20,
      difficulty: 'Beginner',
      icon: Icons.bathtub,
      color: Colors.cyan,
      estimatedTime: '10 min',
    ),
    'living_room': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.chair,
      color: Colors.brown,
      estimatedTime: '12 min',
    ),
    'bedroom': TopicConfig(
      totalWords: 20,
      difficulty: 'Beginner',
      icon: Icons.bed,
      color: Colors.purple,
      estimatedTime: '10 min',
    ),
    'transportation': TopicConfig(
      totalWords: 35,
      difficulty: 'Beginner',
      icon: Icons.directions_bus,
      color: Colors.grey,
      estimatedTime: '18 min',
    ),
    'vehicles': TopicConfig(
      totalWords: 30,
      difficulty: 'Beginner',
      icon: Icons.car_rental,
      color: Colors.blueGrey,
      estimatedTime: '15 min',
    ),
    'airport': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.airplanemode_active,
      color: Colors.lightBlue,
      estimatedTime: '20 min',
    ),
    'hotel': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.hotel,
      color: Colors.deepOrange,
      estimatedTime: '15 min',
    ),
    'restaurant': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.restaurant,
      color: Colors.red,
      estimatedTime: '18 min',
    ),
    'shopping': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.shopping_cart,
      color: Colors.green,
      estimatedTime: '20 min',
    ),
    'money': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.attach_money,
      color: Colors.greenAccent,
      estimatedTime: '12 min',
    ),
    'bank': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.account_balance,
      color: Colors.blue,
      estimatedTime: '15 min',
    ),
    'post_office': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.mail,
      color: Colors.brown,
      estimatedTime: '10 min',
    ),
    'hospital': TopicConfig(
      totalWords: 45,
      difficulty: 'Intermediate',
      icon: Icons.local_hospital,
      color: Colors.red,
      estimatedTime: '22 min',
    ),
    'doctor': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.medical_services,
      color: Colors.pink,
      estimatedTime: '15 min',
    ),
    'pharmacy': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.medication,
      color: Colors.teal,
      estimatedTime: '12 min',
    ),
    'sports': TopicConfig(
      totalWords: 50,
      difficulty: 'Intermediate',
      icon: Icons.sports_soccer,
      color: Colors.orange,
      estimatedTime: '25 min',
    ),
    'music': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.music_note,
      color: Colors.purple,
      estimatedTime: '18 min',
    ),
    'movies': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.movie,
      color: Colors.deepPurple,
      estimatedTime: '15 min',
    ),
    'books': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.menu_book,
      color: Colors.brown,
      estimatedTime: '12 min',
    ),
    'technology': TopicConfig(
      totalWords: 45,
      difficulty: 'Intermediate',
      icon: Icons.computer,
      color: Colors.blue,
      estimatedTime: '22 min',
    ),
    'internet': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.wifi,
      color: Colors.lightBlue,
      estimatedTime: '18 min',
    ),
    'social_media': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.share,
      color: Colors.blueAccent,
      estimatedTime: '15 min',
    ),
    'email': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.email,
      color: Colors.grey,
      estimatedTime: '10 min',
    ),
    'phone': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.phone,
      color: Colors.green,
      estimatedTime: '12 min',
    ),
    'travel': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.explore,
      color: Colors.teal,
      estimatedTime: '20 min',
    ),
    'nature': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.nature,
      color: Colors.green,
      estimatedTime: '18 min',
    ),
    'plants': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.local_florist,
      color: Colors.lightGreen,
      estimatedTime: '15 min',
    ),
    'insects': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.bug_report,
      color: Colors.brown,
      estimatedTime: '12 min',
    ),
    'birds': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.flight,
      color: Colors.blue,
      estimatedTime: '15 min',
    ),
    'sea_life': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.water,
      color: Colors.blueAccent,
      estimatedTime: '18 min',
    ),
    'space': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.space_dashboard,
      color: Colors.indigo,
      estimatedTime: '15 min',
    ),
    'science': TopicConfig(
      totalWords: 50,
      difficulty: 'Advanced',
      icon: Icons.science,
      color: Colors.deepPurple,
      estimatedTime: '25 min',
    ),
    'mathematics': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.calculate,
      color: Colors.orange,
      estimatedTime: '20 min',
    ),
    'history': TopicConfig(
      totalWords: 45,
      difficulty: 'Advanced',
      icon: Icons.history,
      color: Colors.brown,
      estimatedTime: '22 min',
    ),
    'geography': TopicConfig(
      totalWords: 50,
      difficulty: 'Advanced',
      icon: Icons.public,
      color: Colors.green,
      estimatedTime: '25 min',
    ),
    'politics': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.gavel,
      color: Colors.red,
      estimatedTime: '20 min',
    ),
    'law': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.scale,
      color: Colors.blueGrey,
      estimatedTime: '18 min',
    ),
    'economy': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.monetization_on,
      color: Colors.green,
      estimatedTime: '20 min',
    ),
    'business': TopicConfig(
      totalWords: 45,
      difficulty: 'Advanced',
      icon: Icons.business,
      color: Colors.orange,
      estimatedTime: '22 min',
    ),
    'marketing': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.bar_chart,
      color: Colors.pink,
      estimatedTime: '18 min',
    ),
    'advertising': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.ad_units,
      color: Colors.teal,
      estimatedTime: '15 min',
    ),
    'management': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.manage_accounts,
      color: Colors.blue,
      estimatedTime: '18 min',
    ),
    'human_resources': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.group,
      color: Colors.purple,
      estimatedTime: '15 min',
    ),
    'education': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.school,
      color: Colors.blue,
      estimatedTime: '20 min',
    ),
    'psychology': TopicConfig(
      totalWords: 45,
      difficulty: 'Advanced',
      icon: Icons.psychology,
      color: Colors.pink,
      estimatedTime: '22 min',
    ),
    'philosophy': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.menu_book,
      color: Colors.brown,
      estimatedTime: '18 min',
    ),
    'religion': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.volunteer_activism,
      color: Colors.deepOrange,
      estimatedTime: '20 min',
    ),
    'art': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.palette,
      color: Colors.purple,
      estimatedTime: '18 min',
    ),
    'fashion': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.checkroom,
      color: Colors.pink,
      estimatedTime: '15 min',
    ),
    'beauty': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.self_improvement,
      color: Colors.red,
      estimatedTime: '12 min',
    ),
    'cooking': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.restaurant_menu,
      color: Colors.orange,
      estimatedTime: '20 min',
    ),
    'baking': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.cake,
      color: Colors.brown,
      estimatedTime: '15 min',
    ),
    'gardening': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.nature_people,
      color: Colors.green,
      estimatedTime: '18 min',
    ),
    'fishing': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.holiday_village,
      color: Colors.blue,
      estimatedTime: '12 min',
    ),
    'hiking': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.terrain,
      color: Colors.greenAccent,
      estimatedTime: '15 min',
    ),
    'camping': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.forest,
      color: Colors.brown,
      estimatedTime: '18 min',
    ),
    'photography': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.camera,
      color: Colors.grey,
      estimatedTime: '20 min',
    ),
    'painting': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.brush,
      color: Colors.deepPurple,
      estimatedTime: '15 min',
    ),
    'sculpture': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.emoji_objects,
      color: Colors.brown,
      estimatedTime: '12 min',
    ),
    'dance': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.sports_gymnastics,
      color: Colors.pink,
      estimatedTime: '15 min',
    ),
    'theater': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.theaters,
      color: Colors.red,
      estimatedTime: '18 min',
    ),
    'opera': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.music_note,
      color: Colors.deepPurple,
      estimatedTime: '12 min',
    ),
    'ballet': TopicConfig(
      totalWords: 20,
      difficulty: 'Advanced',
      icon: Icons.sports_gymnastics,
      color: Colors.pink,
      estimatedTime: '10 min',
    ),
    'fitness': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.fitness_center,
      color: Colors.green,
      estimatedTime: '18 min',
    ),
    'yoga': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.sports_gymnastics,
      color: Colors.lightGreen,
      estimatedTime: '12 min',
    ),
    'meditation': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.spa,
      color: Colors.teal,
      estimatedTime: '10 min',
    ),
    'health': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.favorite,
      color: Colors.red,
      estimatedTime: '20 min',
    ),
    'nutrition': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.restaurant_menu,
      color: Colors.green,
      estimatedTime: '18 min',
    ),
    'diet': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.line_weight,
      color: Colors.orange,
      estimatedTime: '15 min',
    ),
    'sleep': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.bedtime,
      color: Colors.purple,
      estimatedTime: '10 min',
    ),
    'stress': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.sports_esports,
      color: Colors.blueGrey,
      estimatedTime: '12 min',
    ),
    'happiness': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.sentiment_satisfied,
      color: Colors.yellow,
      estimatedTime: '10 min',
    ),
    'sadness': TopicConfig(
      totalWords: 15,
      difficulty: 'Intermediate',
      icon: Icons.sentiment_dissatisfied,
      color: Colors.grey,
      estimatedTime: '8 min',
    ),
    'anger': TopicConfig(
      totalWords: 15,
      difficulty: 'Intermediate',
      icon: Icons.sentiment_very_dissatisfied,
      color: Colors.red,
      estimatedTime: '8 min',
    ),
    'fear': TopicConfig(
      totalWords: 15,
      difficulty: 'Intermediate',
      icon: Icons.warning,
      color: Colors.orange,
      estimatedTime: '8 min',
    ),
    'love': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.favorite,
      color: Colors.pink,
      estimatedTime: '12 min',
    ),
    'friendship': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.group,
      color: Colors.blue,
      estimatedTime: '10 min',
    ),
    'relationships': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.people,
      color: Colors.purple,
      estimatedTime: '15 min',
    ),
    'marriage': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.ring_volume,
      color: Colors.red,
      estimatedTime: '12 min',
    ),
    'parenting': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.child_care,
      color: Colors.green,
      estimatedTime: '18 min',
    ),
    'childhood': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.child_friendly,
      color: Colors.yellow,
      estimatedTime: '12 min',
    ),
    'teenagers': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.person,
      color: Colors.blue,
      estimatedTime: '15 min',
    ),
    'elderly': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.elderly,
      color: Colors.grey,
      estimatedTime: '12 min',
    ),
    'jobs': TopicConfig(
      totalWords: 50,
      difficulty: 'Intermediate',
      icon: Icons.work,
      color: Colors.blueGrey,
      estimatedTime: '25 min',
    ),
    'professions': TopicConfig(
      totalWords: 45,
      difficulty: 'Intermediate',
      icon: Icons.engineering,
      color: Colors.orange,
      estimatedTime: '22 min',
    ),
    'interview': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.record_voice_over,
      color: Colors.green,
      estimatedTime: '15 min',
    ),
    'resume': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.description,
      color: Colors.blue,
      estimatedTime: '12 min',
    ),
    'office': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.workspaces_filled,
      color: Colors.grey,
      estimatedTime: '20 min',
    ),
    'meeting': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.groups,
      color: Colors.blue,
      estimatedTime: '15 min',
    ),
    'presentation': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.slideshow,
      color: Colors.purple,
      estimatedTime: '18 min',
    ),
    'negotiation': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.handshake,
      color: Colors.green,
      estimatedTime: '15 min',
    ),
    'leadership': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.military_tech,
      color: Colors.red,
      estimatedTime: '18 min',
    ),
    'teamwork': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.group_work,
      color: Colors.blue,
      estimatedTime: '12 min',
    ),
    'communication': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.chat,
      color: Colors.teal,
      estimatedTime: '20 min',
    ),
    'writing': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.edit,
      color: Colors.blue,
      estimatedTime: '18 min',
    ),
    'reading': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.menu_book,
      color: Colors.brown,
      estimatedTime: '15 min',
    ),
    'listening': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.headphones,
      color: Colors.grey,
      estimatedTime: '12 min',
    ),
    'speaking': TopicConfig(
      totalWords: 30,
      difficulty: 'Beginner',
      icon: Icons.record_voice_over,
      color: Colors.orange,
      estimatedTime: '15 min',
    ),
    'grammar': TopicConfig(
      totalWords: 50,
      difficulty: 'Advanced',
      icon: Icons.text_snippet,
      color: Colors.blueGrey,
      estimatedTime: '25 min',
    ),
    'verbs': TopicConfig(
      totalWords: 60,
      difficulty: 'Intermediate',
      icon: Icons.run_circle,
      color: Colors.green,
      estimatedTime: '30 min',
    ),
    'nouns': TopicConfig(
      totalWords: 70,
      difficulty: 'Beginner',
      icon: Icons.label,
      color: Colors.blue,
      estimatedTime: '35 min',
    ),
    'adjectives': TopicConfig(
      totalWords: 50,
      difficulty: 'Intermediate',
      icon: Icons.format_paint,
      color: Colors.purple,
      estimatedTime: '25 min',
    ),
    'adverbs': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.speed,
      color: Colors.orange,
      estimatedTime: '20 min',
    ),
    'prepositions': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.swap_horiz,
      color: Colors.teal,
      estimatedTime: '15 min',
    ),
    'conjunctions': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.link,
      color: Colors.blue,
      estimatedTime: '10 min',
    ),
    'pronouns': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.person,
      color: Colors.pink,
      estimatedTime: '12 min',
    ),
    'articles': TopicConfig(
      totalWords: 10,
      difficulty: 'Beginner',
      icon: Icons.article,
      color: Colors.grey,
      estimatedTime: '5 min',
    ),
    'phrasal_verbs': TopicConfig(
      totalWords: 50,
      difficulty: 'Advanced',
      icon: Icons.change_circle,
      color: Colors.deepOrange,
      estimatedTime: '25 min',
    ),
    'idioms': TopicConfig(
      totalWords: 60,
      difficulty: 'Advanced',
      icon: Icons.auto_stories,
      color: Colors.brown,
      estimatedTime: '30 min',
    ),
    'slang': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.mic,
      color: Colors.pink,
      estimatedTime: '20 min',
    ),
    'collocations': TopicConfig(
      totalWords: 50,
      difficulty: 'Advanced',
      icon: Icons.join_full,
      color: Colors.blue,
      estimatedTime: '25 min',
    ),
    'synonyms': TopicConfig(
      totalWords: 60,
      difficulty: 'Advanced',
      icon: Icons.compare_arrows,
      color: Colors.green,
      estimatedTime: '30 min',
    ),
    'antonyms': TopicConfig(
      totalWords: 50,
      difficulty: 'Advanced',
      icon: Icons.swap_vertical_circle,
      color: Colors.red,
      estimatedTime: '25 min',
    ),
    'homophones': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.hearing,
      color: Colors.blue,
      estimatedTime: '15 min',
    ),
    'prefixes': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.format_indent_decrease,
      color: Colors.purple,
      estimatedTime: '18 min',
    ),
    'suffixes': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.format_indent_increase,
      color: Colors.orange,
      estimatedTime: '18 min',
    ),
    'abbreviations': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.short_text,
      color: Colors.grey,
      estimatedTime: '20 min',
    ),
    'acronyms': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.text_fields,
      color: Colors.blue,
      estimatedTime: '15 min',
    ),
    'punctuation': TopicConfig(
      totalWords: 20,
      difficulty: 'Beginner',
      icon: Icons.title,
      color: Colors.brown,
      estimatedTime: '10 min',
    ),
    'capitalization': TopicConfig(
      totalWords: 15,
      difficulty: 'Beginner',
      icon: Icons.format_size,
      color: Colors.blueGrey,
      estimatedTime: '8 min',
    ),
    'spelling': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.edit,
      color: Colors.red,
      estimatedTime: '20 min',
    ),
    'pronunciation': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.volume_up,
      color: Colors.green,
      estimatedTime: '18 min',
    ),
    'accent': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.language,
      color: Colors.deepPurple,
      estimatedTime: '12 min',
    ),
    'dialects': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.public,
      color: Colors.orange,
      estimatedTime: '15 min',
    ),
    'translation': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.translate,
      color: Colors.blue,
      estimatedTime: '18 min',
    ),
    'interpreting': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.record_voice_over,
      color: Colors.teal,
      estimatedTime: '15 min',
    ),
    'bilingual': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.language,
      color: Colors.green,
      estimatedTime: '10 min',
    ),
    'multilingual': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.public,
      color: Colors.blue,
      estimatedTime: '12 min',
    ),
    'language_learning': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.school,
      color: Colors.orange,
      estimatedTime: '20 min',
    ),
    'fluency': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.mic,
      color: Colors.green,
      estimatedTime: '12 min',
    ),
    'vocabulary': TopicConfig(
      totalWords: 50,
      difficulty: 'All Levels',
      icon: Icons.library_books,
      color: Colors.deepPurple,
      estimatedTime: '25 min',
    ),
    'conversation': TopicConfig(
      totalWords: 45,
      difficulty: 'Intermediate',
      icon: Icons.chat_bubble,
      color: Colors.blue,
      estimatedTime: '22 min',
    ),
    'debate': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.record_voice_over,
      color: Colors.red,
      estimatedTime: '18 min',
    ),
    'public_speaking': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.mic,
      color: Colors.orange,
      estimatedTime: '20 min',
    ),
    'storytelling': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.auto_stories,
      color: Colors.purple,
      estimatedTime: '15 min',
    ),
    'poetry': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.menu_book,
      color: Colors.brown,
      estimatedTime: '18 min',
    ),
    'essays': TopicConfig(
      totalWords: 40,
      difficulty: 'Advanced',
      icon: Icons.description,
      color: Colors.blue,
      estimatedTime: '20 min',
    ),
    'reports': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.assignment,
      color: Colors.green,
      estimatedTime: '18 min',
    ),
    'letters': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.mail,
      color: Colors.blueGrey,
      estimatedTime: '15 min',
    ),
    'emails': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.email,
      color: Colors.blue,
      estimatedTime: '18 min',
    ),
    'social_skills': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.group,
      color: Colors.pink,
      estimatedTime: '20 min',
    ),
    'etiquette': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.how_to_reg,
      color: Colors.brown,
      estimatedTime: '15 min',
    ),
    'manners': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.sentiment_satisfied,
      color: Colors.green,
      estimatedTime: '12 min',
    ),
    'customs': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.public,
      color: Colors.deepPurple,
      estimatedTime: '18 min',
    ),
    'traditions': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.volunteer_activism,
      color: Colors.orange,
      estimatedTime: '15 min',
    ),
    'festivals': TopicConfig(
      totalWords: 40,
      difficulty: 'Intermediate',
      icon: Icons.celebration,
      color: Colors.red,
      estimatedTime: '20 min',
    ),
    'holidays': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.beach_access,
      color: Colors.lightBlue,
      estimatedTime: '18 min',
    ),
    'birthdays': TopicConfig(
      totalWords: 25,
      difficulty: 'Beginner',
      icon: Icons.cake,
      color: Colors.pink,
      estimatedTime: '12 min',
    ),
    'weddings': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.ring_volume,
      color: Colors.red,
      estimatedTime: '15 min',
    ),
    'funerals': TopicConfig(
      totalWords: 20,
      difficulty: 'Advanced',
      icon: Icons.chair,
      color: Colors.grey,
      estimatedTime: '10 min',
    ),
    'graduation': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.school,
      color: Colors.blue,
      estimatedTime: '12 min',
    ),
    'retirement': TopicConfig(
      totalWords: 20,
      difficulty: 'Advanced',
      icon: Icons.holiday_village,
      color: Colors.green,
      estimatedTime: '10 min',
    ),
    'success': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.emoji_events,
      color: Colors.yellow,
      estimatedTime: '15 min',
    ),
    'failure': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.sentiment_dissatisfied,
      color: Colors.grey,
      estimatedTime: '10 min',
    ),
    'motivation': TopicConfig(
      totalWords: 35,
      difficulty: 'Intermediate',
      icon: Icons.rocket_launch,
      color: Colors.orange,
      estimatedTime: '18 min',
    ),
    'goals': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.flag,
      color: Colors.green,
      estimatedTime: '12 min',
    ),
    'dreams': TopicConfig(
      totalWords: 30,
      difficulty: 'Intermediate',
      icon: Icons.bedtime,
      color: Colors.purple,
      estimatedTime: '15 min',
    ),
    'ambition': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.trending_up,
      color: Colors.blue,
      estimatedTime: '12 min',
    ),
    'courage': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.military_tech,
      color: Colors.red,
      estimatedTime: '10 min',
    ),
    'patience': TopicConfig(
      totalWords: 15,
      difficulty: 'Intermediate',
      icon: Icons.hourglass_bottom,
      color: Colors.brown,
      estimatedTime: '8 min',
    ),
    'kindness': TopicConfig(
      totalWords: 20,
      difficulty: 'Beginner',
      icon: Icons.volunteer_activism,
      color: Colors.green,
      estimatedTime: '10 min',
    ),
    'honesty': TopicConfig(
      totalWords: 20,
      difficulty: 'Intermediate',
      icon: Icons.verified,
      color: Colors.blue,
      estimatedTime: '10 min',
    ),
    'loyalty': TopicConfig(
      totalWords: 15,
      difficulty: 'Intermediate',
      icon: Icons.favorite,
      color: Colors.pink,
      estimatedTime: '8 min',
    ),
    'justice': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.gavel,
      color: Colors.blueGrey,
      estimatedTime: '12 min',
    ),
    'freedom': TopicConfig(
      totalWords: 20,
      difficulty: 'Advanced',
      icon: Icons.flag,
      color: Colors.green,
      estimatedTime: '10 min',
    ),
    'equality': TopicConfig(
      totalWords: 25,
      difficulty: 'Advanced',
      icon: Icons.balance,
      color: Colors.purple,
      estimatedTime: '12 min',
    ),
    'democracy': TopicConfig(
      totalWords: 30,
      difficulty: 'Advanced',
      icon: Icons.how_to_vote,
      color: Colors.blue,
      estimatedTime: '15 min',
    ),
    'war': TopicConfig(
      totalWords: 35,
      difficulty: 'Advanced',
      icon: Icons.military_tech,
      color: Colors.grey,
      estimatedTime: '18 min',
    ),
    'peace': TopicConfig(
      totalWords: 25,
      difficulty: 'Intermediate',
      icon: Icons.self_improvement,
      color: Colors.green,
      estimatedTime: '12 min',
    ),
  };

  static const TopicConfig _defaultConfig = TopicConfig(
    totalWords: 20,
    difficulty: 'Beginner',
    icon: Icons.book,
    color: Colors.grey,
    estimatedTime: '12 min',
  );

  /// Get topic configuration by topic name
  static TopicConfig getTopicConfig(String topicName) {
    return _topicConfigs[topicName] ?? _defaultConfig;
  }

  /// Get all topic configurations
  static Map<String, TopicConfig> getAllTopicConfigs() {
    return Map.from(_topicConfigs);
  }

  /// Get topic data as Map (for backward compatibility)
  static Map<String, dynamic> getTopicData(String topicName) {
    final config = getTopicConfig(topicName);
    return {
      'totalWords': config.totalWords,
      'difficulty': config.difficulty,
      'icon': config.icon,
      'color': config.color,
      'estimatedTime': config.estimatedTime,
    };
  }

  /// Check if topic exists
  static bool hasTopicConfig(String topicName) {
    return _topicConfigs.containsKey(topicName);
  }

  /// Get all topic names
  static List<String> getAllTopicNames() {
    return _topicConfigs.keys.toList();
  }
}
