// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ZUQ1m-ICX3jE-oVKfsmRVOJaRg4IWy4',
    appId: '1:387492232517:web:ca15bf2c5e1f40047fd22c',
    messagingSenderId: '387492232517',
    projectId: 'bvoca-68c89',
    authDomain: 'bvoca-68c89.firebaseapp.com',
    databaseURL: 'https://bvoca-68c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bvoca-68c89.firebasestorage.app',
    measurementId: 'G-D84EE1QKW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZr2ZtmZx2_GKHxZdeil8LFvuP0mi-xOU',
    appId: '1:387492232517:android:6b0cdbc3ed18ebc07fd22c',
    messagingSenderId: '387492232517',
    projectId: 'bvoca-68c89',
    databaseURL: 'https://bvoca-68c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bvoca-68c89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCutg_UjZ4_hITftyXqCYuTzWuDoMq3vAA',
    appId: '1:387492232517:ios:d8a3ec5a7407f9317fd22c',
    messagingSenderId: '387492232517',
    projectId: 'bvoca-68c89',
    databaseURL: 'https://bvoca-68c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bvoca-68c89.firebasestorage.app',
    iosClientId: '387492232517-ied2nkf0ehn20qaf14rk59bn6gk8jf01.apps.googleusercontent.com',
    iosBundleId: 'com.example.bvo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCutg_UjZ4_hITftyXqCYuTzWuDoMq3vAA',
    appId: '1:387492232517:ios:d8a3ec5a7407f9317fd22c',
    messagingSenderId: '387492232517',
    projectId: 'bvoca-68c89',
    databaseURL: 'https://bvoca-68c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bvoca-68c89.firebasestorage.app',
    iosClientId: '387492232517-ied2nkf0ehn20qaf14rk59bn6gk8jf01.apps.googleusercontent.com',
    iosBundleId: 'com.example.bvo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4ZUQ1m-ICX3jE-oVKfsmRVOJaRg4IWy4',
    appId: '1:387492232517:web:69b7a14568cfa3107fd22c',
    messagingSenderId: '387492232517',
    projectId: 'bvoca-68c89',
    authDomain: 'bvoca-68c89.firebaseapp.com',
    databaseURL: 'https://bvoca-68c89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bvoca-68c89.firebasestorage.app',
    measurementId: 'G-GQ1Q13RMNM',
  );
}
